name: Continuous Integration and Documentation

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        working-directory: ./backend/spring-boot-h2-database-crud
      - name: Run Unit Tests
        run: mvn test
        working-directory: ./backend/spring-boot-h2-database-crud

  

  generate-and-publish-docs:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Generate Backend Documentation
      run: |
        cd ./backend/spring-boot-h2-database-crud
        chmod +x ./mvnw
        ./mvnw javadoc:javadoc

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Generate Frontend Documentation
      run: |
        cd ./frontend/vue-3-crud
        npm install
        npm run jsdoc

    - name: Copy Documentation to DOCS Directory
      run: |
        mkdir -p DOCS/backend
        mkdir -p DOCS/frontend
        cp -r ./backend/spring-boot-h2-database-crud/target/site/apidocs/* DOCS/backend/
        cp -r ./frontend/vue-3-crud/docs/* DOCS/frontend/

    - name: Create Central Landing Page
      run: |
        echo '<!DOCTYPE html>
        <html>
        <head>
            <title>TFSD Practical Work 5-8: Task Management Full Stack Application Documentation</title>
        </head>
        <body>
            <h1>TFSD Practical Work 5-8: Task Management Full Stack Application Documentation</h1>
        
            <h2>Introduction</h2>
            <p>Developed by Julien Séailles, this application provides a robust platform for task management. It combines a Spring Boot backend with a Vue 3 frontend, offering a responsive and dynamic user interface.</p>
        
            <h2>Installation and Setup</h2>
            <h3>Backend</h3>
            <ul>
                <li>Clone the backend repository.</li>
                <li>Navigate to the backend directory and install dependencies with Maven.</li>
                <li>Start the Spring Boot application.</li>
                <li>The server starts on <code>http://localhost:8080</code>.</li>
                <li>Detailed setup instructions are available <a href="https://github.com/Themask3d/TFSD/blob/main/backend/spring-boot-h2-database-crud/README.md">here</a>.</li>
            </ul>
        
            <h3>Frontend</h3>
            <ul>
                <li>Clone the frontend repository.</li>
                <li>Navigate to the frontend directory and install dependencies using NPM.</li>
                <li>Start the Vue application with <code>npm run serve</code>.</li>
                <li>Access the frontend at <code>http://localhost:8081</code>.</li>
                <li>Further setup details can be found <a href="https://github.com/Themask3d/TFSD/blob/main/frontend/vue-3-crud/README.md">here</a>.</li>
            </ul>
        
            <h2>Core Functionalities</h2>
            <h3>Backend</h3>
            <ul>
                <li>Provides CRUD operations for task management.</li>
                <li>Utilizes H2 Database for data persistence.</li>
                <li>RESTful API for frontend interaction.</li>
                <li>Explore API details in the <a href="./backend/index.html">Backend API Reference</a>.</li>
            </ul>
        
            <h3>Frontend</h3>
            <ul>
                <li>User-friendly interface for task management.</li>
                <li>Implements real-time data interaction using Axios.</li>
                <li>Responsive design with Bootstrap.</li>
                <li>UI components are detailed <a href="./frontend/index.html">here</a>.</li>
            </ul>
        
            <h2>Technical Documentation</h2>
            <ul>
                <li>Backend code, such as <code>TutorialController.java</code>, can be found <a href="https://github.com/Themask3d/TFSD/blob/main/backend/spring-boot-h2-database-crud/src/main/java/com/bezkoder/spring/jpa/h2/controller/TutorialController.java">here</a>.</li>
                <li>Frontend code, including <code>AddTutorial.vue</code>, is available <a href="https://github.com/Themask3d/TFSD/blob/main/backend/spring-boot-h2-database-crud/src/main/java/com/bezkoder/spring/jpa/h2/model/Tutorial.java">here</a>.</li>
                <li>Examples of API usage and additional resources are in the tests: <a href="https://github.com/Themask3d/TFSD/tree/main/backend/spring-boot-h2-database-crud/src/test/java/com/bezkoder/spring/jpa/h2/controller">here</a>.</li>
            </ul>
        
            <h2>API Usage Examples</h2>
            <ul>
                <li><strong>Create Task</strong>: Endpoint for creating a new task. Example: <code>POST /api/tutorials</code>.</li>
                <li><strong>Update Task</strong>: Update existing tasks. Example: <code>PUT /api/tutorials/{id}</code>.</li>
                <li><strong>Delete Task</strong>: Remove a task. Example: <code>DELETE /api/tutorials/{id}</code>.</li>
            </ul>
        
            <h2>Contributing</h2>
            <p>Contributors are welcome to fork the repository, create feature branches, and submit pull requests. Contribution guidelines are available <a href="https://github.com/Themask3d/TFSD/blob/main/README.md">here</a>.</p>
        
            <h2>License</h2>
            <p>This project is under the MIT License, detailed in the <a href="https://github.com/Themask3d/TFSD/blob/main/LICENSE.md">LICENSE</a> file.</p>
        
            <h2>Contact</h2>
            <p>Julien Séailles: <a href="https://github.com/Themask3d">Themask3d</a></p>
            <p>Project Repository: <a href="https://github.com/Themask3d/TFSD">TFSD Full Stack Project</a></p>
        
            <hr>
        </body>
        </html>' > DOCS/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./DOCS

  create-release:
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: |
            backend/target/*.jar
            frontend/dist/*
            combined-docs/
