name: Java CI with Maven

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: ./backend/spring-boot-h2-database-crud

    - name: Run Unit Tests
      run: mvn test
      working-directory: ./backend/spring-boot-h2-database-crud

    # Only execute the following steps if this push is for a tag
    - if: startsWith(github.ref, 'refs/tags/')
      name: Zip Backend Directory
      run: zip -r backend.zip ./backend/spring-boot-h2-database-crud/
      
    - if: startsWith(github.ref, 'refs/tags/')
      name: Zip Frontend Directory
      run: zip -r frontend.zip ./frontend/vue-3-crud/
      
    - if: startsWith(github.ref, 'refs/tags/')
      name: Zip Full-stack Directory
      run: |
        zip -r full-stack.zip ./backend/spring-boot-h2-database-crud/ \
                                ./frontend/vue-3-crud/ \
                                LICENSE.md README.md docker-compose.yml
      
    - if: startsWith(github.ref, 'refs/tags/')
      name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - if: startsWith(github.ref, 'refs/tags/')
      name: Upload Backend Artifact to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./backend.zip
        asset_name: backend.zip
        asset_content_type: application/zip

    - if: startsWith(github.ref, 'refs/tags/')
      name: Upload Frontend Artifact to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./frontend.zip
        asset_name: frontend.zip
        asset_content_type: application/zip

    - if: startsWith(github.ref, 'refs/tags/')
      name: Upload Full-stack Artifact to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./full-stack.zip
        asset_name: full-stack.zip
        asset_content_type: application/zip
