name: Continuous Integration and Documentation

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        working-directory: ./backend/spring-boot-h2-database-crud
      - name: Run Unit Tests
        run: mvn test
        working-directory: ./backend/spring-boot-h2-database-crud

  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Backend Documentation
        run: |
          # Step 1: Ensure all dependencies are downloaded
          mvn dependency:resolve

          # Step 2: Build the classpath
          mvn dependency:build-classpath -Dmdep.outputFile=classpath.txt

          # Step 3: Read the classpath into a variable
          CLASSPATH=$(cat classpath.txt)

          # Step 4: Run javadoc with the classpath
          javadoc -d backend/Technical\ documentation -sourcepath backend/spring-boot-h2-database-crud/src/main/java -classpath "$CLASSPATH" -subpackages com.bezkoder.spring.jpa.h2
        working-directory: ./backend/spring-boot-h2-database-crud



      - name: Generate Frontend Documentation
        run: |
          npm install -g jsdoc
          jsdoc -d frontend/vue-3-crud/docs frontend/vue-3-crud/src
      - name: Combine Documentation
        run: |
          mkdir -p combined-docs/backend
          mkdir -p combined-docs/frontend
          cp -r backend/Technical\ documentation/* combined-docs/backend/
          cp -r frontend/vue-3-crud/docs/* combined-docs/frontend/
      - name: Deploy Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./combined-docs

  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: |
            backend/target/*.jar
            frontend/dist/*
            combined-docs/
